### PR TITLE
microcommit: open links in new tab

### PR DESCRIPTION
**Pull request by kodedninja**
I think it would be better if links in the entries would open in new tab.

### CODE REVIEW

**Comment by saulhardman** [comment]
Chiming in: shouldn't we leave this up to the user? E.g. `Right-click > Open Link in New Tab` or `⌘ + Click`.

Introduces a possible vulnerability too: https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/

**Comment by kodedninja** [comment]
@saulhardman Thanks for the vulnerability! The ```Right-click > Open Link``` way is pretty annoying in my opinion, because most of the time you want to see the content and come back to the page. Also Rotonde loads pretty slow.

I'll fix the vulnerability with ```rel="noopener"``` and let's see what others say. :)

**Comment by yhancik** [comment]
I tend to open a lot of new tabs, but I also believe it's best practice to leave the user chose if they want a new tab or not.
(also don't we all open new tabs with middle-click?)

**Comment by kodedninja** [comment]
@yhancik what about laptop guys? :P

**Comment by yhancik** [comment]
Oh yes I tend to forget that! I can't stand trackpads so I always use a mouse regardless :p

**Comment by kodedninja** [comment]
@yhancik should I close this then or leave it open for now?

**Comment by yhancik** [comment]
No idea! Leave it open for more feedback?

**Comment by 0x0ade** [comment]
LGTM and I'm welcoming this change :) Let's wait for what @neauoire has got to say.

TIL about the `target='_blank'` vulnerability.

**Comment by neauoire** [comment]
That's something I will use a lot.

**Pull request merged**
