### PR TITLE
Revert "Add oembed support"

### PR DESCRIPTION
**Pull request by neauoire**
Reverts Rotonde/rotonde-client#161

### CODE REVIEW

**Comment by 0x0ade** [comment]
Any plans to add embed support back?

**Comment by neauoire** [comment]
How do I revert back to this change now? :|

**Comment by 0x0ade** [comment]
Maybe `git revert 8b8a5b457b8aa85bb209d871c0f4450c4b595a5f` ?

**Comment by neauoire** [comment]
$__$ done

**Pull request merged**
