### PR TITLE
Potential fix for disappearing tabs on discovery and portals pages

### PR DESCRIPTION
**Pull request by manpat**
hey this is a quick solution I found to the disappearing tabs issue.
the fix works for me and the handful of other portals I tried it on but can't guarantee it won't break someones styling somewhere

for reference - my portal: dat://a5341c28d55680dfbe073df05a01e9d58591a782e5ca252d60b2ce62935b4498/

hope random pull requests are okay!

### CODE REVIEW

**Comment by neauoire** [comment]
cheers Patrick 👍

**Comment by neauoire** [comment]
Seeding

**Comment by manpat** [comment]
glad I could help!

**Comment by eelfroth** [comment]
yeah, seems to work fine :)
I was going to put `#operator` and `#tabs` together in a wrapper and make _that_ `position:fixed; top:0px;`, but it seems now I won't have to

**Pull request merged**
