### PR TITLE
Attempted Whisper/Media Fix

### PR DESCRIPTION
**Pull request by alphaflood**
Whispering with attached media was throwing an error. Simply reordering the existing lines of code a little seems to remedy the issue.

### CODE REVIEW

**Comment by alphaflood** [comment]
Hm. On closer inspection, it does seem to formulate the proper insert into portal.json, but crashes seemed more likely when my feed displayed a whisper with media attached. Not sure why yet.

**Comment by frozenpandaman** [comment]
seems to work for me 👍

image

**Comment by teleben** [comment]
I did additional testing. Looks like it was the gif I was attempting to display. Not sure if it was just that one, or gifs in general. jpg works fine.

**Comment by alphaflood** [comment]
I did additional testing. Looks like it was the gif I was attempting to display. Not sure if it was just that one, or gifs in general. jpg works fine.

**Comment by alphaflood** [comment]
Appears to work with other gifs. The original file I tested with must have been malformed or something. Beaker seems stable now.

**Comment by underscorediscovery** [comment]
what if there's more than one in the chain?

**Comment by alphaflood** [comment]
Hm. I'm not sure. I'm simply reusing the code that already existed in .say().

**Comment by alphaflood** [comment]
I tried piping in another image. It only uses the first and ignores all subsequent media.

Example:

> whisper:alphaflood Test >> image_01.jpg >> image_02.jpg


Currently, only image_01.jpg would be added to portal.json.

**Pull request merged**
