### PR TITLE
[REQUIRES TESTING] WebDB migration

### PR DESCRIPTION
**Pull request by 0x0ade**
- Add support for dependencies loaded before scripts (higher priority)
- Add basic support for the npm package `@beaker/WebDB` and its dependencies by browserify-ing `required-pre.js` into `required.js` (PR comes with prebundled `required.js`)
- New portals have `/profile.json`, not `/portal.json`, but both are supported by Rotonde. (Fritter only sees `/profile.json`)
- Read and write data in Fritter-based format, keeping Rotonde "extensions" (quotes, whispers, discoverable, ...)
- Support legacy feed in `portal.json` / `profile.json`
- Attempt to keep most of Rotonde's code as-is, or close.

This is quite a game changer: https://twitter.com/0x0ade/status/951124592910897152

... but it also means I probably haven't found all bugs yet. Please do the following:

- Make a full backup of your Rotonde portal
- Clone my fork's master branch
- Add it to Beaker
- Change your portal's `index.html` to point to the newly added fork
- Hit buttons

This also means all bots, crawlers, services and alternative Rotonde clients will need to migrate to WebDB soonish.

### CODE REVIEW

**Comment by 0x0ade** [comment]
Something I'm not really a fan of and @cblgh isn't either: The npm package / browserify workflow.

At the moment, `required.js` weighs in at 587K (according to `ls -lh`) and Rotonde was fine without any npm dependencies until now.

Any ideas on how we could solve this?

**Comment by pfrazee** [comment]
What about a webdb bundle that you can <script src=""> to import?

**Comment by 0x0ade** [comment]
Sounds much better 👍

**Comment by neauoire** [comment]
I'm gonna click this.

**Comment by neauoire** [comment]
I clicked this.

**Comment by 0x0ade** [comment]
BUT NAMES WITH SPACES

**Comment by 0x0ade** [comment]
Well, now at least one PR will follow this

**Comment by neauoire** [comment]
The main client is now on 0.4, we know everyone using it. It'll just make finding bugs easier :)

**Pull request merged**
