### PR TITLE
Implements sameAs to use Rotonde from multiple machines

### PR DESCRIPTION
**Pull request by cblgh**
As described in [#147](https://github.com/Rotonde/rotonde-client/issues/147#issuecomment-345389579) `sameAs` is an extension to portal.json. 

It adds an array `sameAs` that contains entries to other portals. If those portals in turn have your portal in their `sameAs` arrays, you are considered **remotes** of each other. 

The entire point is to decouple your Rotonde portal from a single machine. Using this feature you can now:
* see the same feed as your remotes
* others following your portal will see the posts you make **from remotes**
* mentions to either the source portal or its remotes will be visible in the mentions tab

#### Start using it:
If your main portal is `dat://7f2ee...0c5/` and your work computer has a portal at `dat://3ba71...829/`

1. Visit your main portal at `dat://7f2ee...0c5/` and run `mirror dat://3ba71...829/`
1. Visit your work portal at `dat://3ba71...829/` and run `mirror dat://7f2ee...0c5/`
1. You're done! You can now Rotonde from any of the machines with ease.

Remove remotes using the **unmirror** command:
`unmirror dat://7f2ee...0c5/` this severs the link between remotes.

Thanks to @0x0ade for some back and forth across twitter, rotonde and github! :~

### CODE REVIEW

**Comment by neauoire** [comment]
Madness

**Comment by 0x0ade** [comment]
Wow, GitHub just automatically mirrors our comments here!

Also, 🎉 great work!

**Comment by neauoire** [comment]
Has Paul seen this?

**Comment by neauoire** [comment]
Who wants to have the honour of pressing merge?

**Comment by 0x0ade** [comment]
I'm imagining you two staring with a dead-serious glaze at the screen, cursor over the merge button, finger over the mouse button... 🍿

**Comment by pfrazee** [comment]
Just read the high level description, looks like a solid solution.

**Comment by neauoire** [comment]
I got Paul's blessing, I'm merging.

**Pull request merged**
